// `hive up` / `hive down`: run Hive Core with Docker Compose. Secrets are generated locally on first use into an
// ignored .env file (never committed, never printed). Profiles add optional pieces: ui (gateway with shell and console).
import {execFileSync} from 'node:child_process';
import {randomBytes} from 'node:crypto';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';

export function composeFiles(root) {
 return {file:join(root,'infra/docker-compose/hive.yml'),env:join(root,'infra/docker-compose/.env')};
}

export function ensureEnv(envFile,overrides={}) {
 const existing=existsSync(envFile)?Object.fromEntries(readFileSync(envFile,'utf8').split(/\r?\n/).filter(l=>l.includes('=')&&!l.startsWith('#')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)])):{};
 const secret=()=>randomBytes(32).toString('hex');
 const values={HIVE_DB_PASSWORD:secret(),HIVE_GRAPH_PASSWORD:secret(),HIVE_REDIS_PASSWORD:secret(),HIVE_INTERNAL_PASSWORD:secret(),HIVE_PROVISIONING_PASSWORD:secret(),
  HIVE_VAULT_KEY:randomBytes(32).toString('base64'),HIVE_HTTP_PORT:'8080',...existing,...overrides};
 writeFileSync(envFile,'# Generated by hive up. Local secrets: do not commit.\n'+Object.entries(values).map(([k,v])=>`${k}=${v}`).join('\n')+'\n',{mode:0o600});
 return values;
}

export function compose(root,args,{profiles=[],project='hive',envFile}={}) {
 const {file,env:defaultEnv}=composeFiles(root);const env=envFile??defaultEnv;
 const profileArgs=profiles.flatMap(p=>['--profile',p]);
 return execFileSync('docker',['compose','-p',project,'-f',file,'--env-file',env,...profileArgs,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:600000});
}
